// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://memedzgyvrmknzvwlblq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lbWVkemd5dnJta256dndsYmxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTM2OTMsImV4cCI6MjA1OTUyOTY5M30.5NJGaZ3i3PoWjpBwaAK_aKe-H_PWfvYu3-0Wa54kl28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);